name: '[trigger.pull-request]'

on:
  pull_request:



jobs:
  docker-build-push-cms-base:
    uses: mysticeragames/MakeItStatic-CI/.github/workflows/job.docker-image-makeitstatic-cms-base.yml@main
    permissions:
      contents: read
    with:
      PUSH: 'false'
      RELEASE: 'false'
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
