name: '[trigger.release] Docker build+push release'

on:
  release:
    types:
      - released

jobs:
  docker-build-push-cms-base:
    uses: ./.github/workflows/job.docker-build-push-cms-base.yml
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
