name: '[trigger.main] Pushed/merged to main'

on:
  push:
    branches:
      - main

jobs:
  docker-build-push-cms-base:
    uses: ./.github/workflows/job.docker-build-push-cms-base.yml
    with:
      IS_RELEASE: false
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
