name: '[trigger.main] Pushed/merged to main'

on:
  push:
    branches:
      - main

jobs:
  docker-build-push-cms-base:
    uses: mysticeragames/MakeItStatic-CI/.github/workflows/job.docker-image.yml@main
    permissions:
      contents: read
    with:
      PUSH: 'true'
      RELEASE: 'false'
      TARGET_IMAGE: 'mysticeragames/makeitstatic-cms-base'
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
