name: '[trigger.pull-request]'

on:
  pull_request:



permissions:
  contents: read

jobs:
  docker-build-push-cms-base:
    uses: mysticeragames/MakeItStatic-CI/.github/workflows/job.docker-image-makeitstatic-cms-base.yml@main
    with:
      PUSH: 'false'
      RELEASE: 'false'
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
